# Tokens supported by the the Elusiv Program

[[token]]
symbol = "LAMPORTS"
mint = "11111111111111111111111111111111" # unused
mint_devnet = "11111111111111111111111111111111" # unused
active = true
price_base_exp = 9
min = 1_000
max = 360_000_000_000
# https://pyth.network/price-feeds/crypto-sol-usd
pyth_usd_price_mainnet = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
pyth_usd_price_devnet = "J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix"

[[token]]
symbol = "USDC"
# https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
mint = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
mint_devnet = "F3hocsFVHrdTBG2yEHwnJHAJo4rZfnSwPg8d5nVMNKYE"
active = true
decimals = 6
min = 1_000
max = 8_000_000_000
# https://pyth.network/price-feeds/crypto-usdc-usd
pyth_usd_price_mainnet = "Gnt27xtC473ZT2Mw5u8wZ68Z3gULkSTb5DuxJy7eJotD"
pyth_usd_price_devnet = "5SSkXsEKQepHHAewytPVwdej4epN1nxgLVM84L4KXgy7"

[[token]]
symbol = "USDT"
# https://explorer.solana.com/address/Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
mint = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
mint_devnet = "AyPeYKj4oHBGdhLjMwbj9m8tEdS1gr9tyqkpT3oDEZUV"
active = true
decimals = 6
min = 1_000
max = 8_000_000_000
# https://pyth.network/price-feeds/crypto-usdt-usd
pyth_usd_price_mainnet = "3vxLXJqLqF3JG5TCbYycbKWRBbCJQLxQmBGCkyqEEefL"
pyth_usd_price_devnet = "38xoQ4oeJCBrcVvca2cGk7iV1dAfrmTR1kmhSCJQ8Jto"